
--1

SELECT exam_type, CASE exam_type
WHEN 'MCE' THEN 'OBJECTIVE' 
WHEN 'TF'	THEN 'OBJECTIVE' 
WHEN 'FIB'	THEN 'OBJECTIVE' 
WHEN 'ESS'	THEN 'SUBJECTIVE' 
WHEN 'SA'	THEN 'SUBJECTIVE' 
WHEN 'PS'	THEN 'ANALYTICAL'
WHEN 'LAB'	THEN 'PRACTICAL'
ELSE 'NOT PERMITTED' END "NATURE OF EXAM"
FROM ad_exam_type;

--2

SELECT student_id, marks, CASE 
WHEN marks < 60	THEN 'FAIL'
WHEN marks BETWEEN 60 AND 70	THEN 'SATISFACTORY' 
WHEN marks BETWEEN 70 and 80	THEN 'GOOD'
WHEN marks BETWEEN 80 and 90 THEN 'VERY GOOD' 
WHEN marks BETWEEN 90 and 100 THEN 'EXCELLENT' 
ELSE 'ERROR' END "GRADE REMARK"
FROM ad_exam_results;

--3

SELECT exam_type, DECODE(exam_type,
'MCE','OBJECTIVE',
'TF', 'OBJECTIVE',
'FIB', 'OBJECTIVE',
'ESS', 'SUBJECTIVE',
'SA',	'SUBJECTIVE',
'PS', 'ANALYTICAL',
'LAB', 'PRACTICAL',
'NOT PERMITTED') "NATURE OF EXAM"
FROM ad_exam_type;



